//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogCoupon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int ID { get; set; }
        public Nullable<int> Type { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Note { get; set; }
        public Nullable<int> Cate { get; set; }
        public string Link { get; set; }
        public string Code { get; set; }
        public Nullable<int> SellOff { get; set; }
        public string Branch { get; set; }
        public Nullable<int> PostID { get; set; }
        public string ImgThumb { get; set; }
    }
}
